# Generated by Django 3.2 on 2021-04-24 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(default='player', max_length=25)),
                ('player_country', models.CharField(choices=[('INDIA', 'INDIA'), ('SRI LANKA', 'SRI LANKA'), ('AFGANISTHAN', 'AFGANISTHAN')], max_length=15)),
                ('gender', models.CharField(choices=[('M', 'MALE'), ('F', 'FE_MALE')], max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_field_type', models.CharField(choices=[('BOWLING', 'BOWLING'), ('BATTING', 'BATTING'), ('ALL', 'ALL ROUNDER')], max_length=11)),
                ('match_type', models.CharField(choices=[('ODI', 'ODI'), ('TEST', 'TEST'), ('T20', 'T20')], max_length=5)),
                ('rating', models.IntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PlayerRankings.player')),
            ],
        ),
    ]
